name: Deploy React App to S3

on:
  push:
    branches:
      - main  

jobs:
  build-unittest-deploy-to-test-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clear cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install

      - name: Cache node_modules and Cypress
        uses: actions/upload-artifact@v4
        with:
          name: app-deps
          path: |
            node_modules
            cypress
            cypress.config.js
            package.json
            package-lock.json

      - name: Build React App
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Deploy to S3 Test Bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_TEST_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"  # The default output folder for React builds

  cypress-test:
    needs: build-unittest-deploy-to-test-s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: app-deps

      - name: Run Cypress tests against CloudFront
        uses: cypress-io/github-action@v6
        with:
          wait-on: ${{ secrets.TEST_CLOUDFRONT_URL }}
          wait-on-timeout: 60  # wait up to 60 seconds for the site to be ready
          command: npx cypress run --config baseUrl=${{ secrets.TEST_CLOUDFRONT_URL }} --spec cypress/e2e/smoke.cy.js

  deploy-prod:
    needs: cypress-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: app-deps

      - name: Download built app
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy to S3 Production Bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_PROD_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"

      - name: Smoke test production
        run: npx cypress run --spec cypress/e2e/smoke.cy.js
        env:
          CYPRESS_BASE_URL: ${{ secrets.PRODUCTION_URL }}

